version: "3"

services:
  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules # /app is the WORKDIR we specified in ./server/Dockerfile
      - ./server:/app
    working_dir: /app
    command: ["npm", "run", "start"]
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules # /app is the WORKDIR we specified in ./client/Dockerfile
      - ./client:/app
  nginx:
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "3050:80"
