version: "3"

services:
  api:
    container_name: api
    build:
      context: ./server
      dockerfile: Dockerfile.local
    working_dir: /app
    ports:
      - "3001:3001"
  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile.local
    restart: always
  nginx:
    container_name: nginx
    image: nginx:alpine
    depends_on:
      - api
      - client
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "3040:80"